### ISSUE TITLE
Is this correct Mordrag?

### ISSUE THREAD

**Issue by Bubba-Bubba** [MordragT/nix-templates#1]
You make a project folder & then you initialize the flake in it:
`nix flake init -t github:MordragT/nix-templates#python-poetry`

Create the dev environment:
`nix develop
`
create the project with poetry:
`poetry new my_app`

Enter a virtual environment:
`poetry shell`

..........................

e.g. 

me@nixos:~/Poetry_Projects/Beta]$ tree
.
├── beta
│   ├── beta
│   │   └── __init__.py
│   ├── pyproject.toml
│   ├── README.md
│   └── tests
│       └── __init__.py
├── flake.lock
├── flake.nix
├── package
│   ├── __init__.py
│   ├── __main__.py
│   └── main.py
├── poetry.lock
├── pyproject.toml
├── README.md
└── tests
    ├── __init__.py
    └── test_poetry.py

**Comment by MordragT** [comment]
Hi sorry for the late reply. You dont really have to create the project with poetry as it is already part of the template. So it would just be:

```
nix flake init -t github:MordragT/nix-templates#python-poetry
nix develop
python ./package/
```

I have done that so across all of the different templates but i am considering to let the users initialise their own projects

**Comment by Bubba-Bubba** [comment]
Thanks Mordrag
