### ISSUE TITLE
Stylesheets can not be loaded in reveal.js template

### ISSUE THREAD

**Issue by iFreilicht** [MordragT/nix-templates#2]
The reveal.js remplate is broken. In `index.html`, these lines are supposed to include the themes:

```
  <link rel="stylesheet" href="/node_modules/reveal.js/dist/reveal.css">
  <link rel="stylesheet" href="/node_modules/reveal.js/dist/theme/black.css">
```

But they are missing from vite's output:

![Screenshot 2023-11-02 at 20 31 07](https://github.com/MordragT/nix-templates/assets/9742635/792281d5-f09b-4701-b34d-731ff176c49e)

Not sure how I can tell vite to bundle these files anyway, despite them not appearing in the script.

**Comment by iFreilicht** [comment]
Ok it seems like I'm not entirely correct here. The stylesheets are indeed loaded, but syntax highlighting is broken.

**Comment by iFreilicht** [comment]
Found a fix, submitted a PR.

**Comment by MordragT** [comment]
Ah cool thanks for fixing it !
